language: node_js
node_js:
  - "7"

cache:
  directories:
    - "node_modules"

notifications:
  email:
    - PalBubbles@mailinator.com
    # on_success: never


# notifications:
#   slack:
#     rooms:
#       - <account>:<token>#development
#       - <account>:<token>#general
#     on_success: change # default: always
#     on_failure: always # default: always
